// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzdJQJ18fzP4tiYjiVhczfSa97hCPiOFE',
    appId: '1:1051003350757:web:62d3815f5bba1f7b2c6e0c',
    messagingSenderId: '1051003350757',
    projectId: 'surveywebapp-365be',
    authDomain: 'surveywebapp-365be.firebaseapp.com',
    storageBucket: 'surveywebapp-365be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDe56G0BkXAWEdawEj7WbSYwaU_aKj7P0',
    appId: '1:1051003350757:android:7ce4741c42fea0bf2c6e0c',
    messagingSenderId: '1051003350757',
    projectId: 'surveywebapp-365be',
    storageBucket: 'surveywebapp-365be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-lZkjka5umKLzs51KwQ9uyA4JMouydI8',
    appId: '1:1051003350757:ios:c37692481ef911c12c6e0c',
    messagingSenderId: '1051003350757',
    projectId: 'surveywebapp-365be',
    storageBucket: 'surveywebapp-365be.appspot.com',
    iosClientId: '1051003350757-f69i5drpu5rm3m00eu70cletai8hn52h.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveywebapp',
  );
}
